name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-20.04
                env:
                    CATKIN_WS: /home/runner/work/catkin_ws

                steps:
                - uses: actions/checkout@v2

                - name: Setup_ROS
                  uses: ros-tooling/setup-ros@v0.2
                  with:
                    required-ros-distributions: noetic

                - name: Get Python version
                  run: python -V

                - name: catkin_make
                  run: |
                    mkdir -p ${CATKIN_WS}/src
                    cd ${CATKIN_WS}/src
                    source /opt/ros/noetic/setup.bash
                    catkin_init_workspace
                    cd ${CATKIN_WS}
                    catkin_make

                - name: setup bash
                  run: |
                    ls /etc/ros/rosdep/sources.list.d/20-default.list && sudo rm -f /etc/ros/rosdep/sources.list.d/20-default.list
                    sudo apt install -y python3-pip
                    sudo apt-get install python3-rosdep
                    sudo rosdep init 
                    rosdep update

                    grep -F "source /opt/ros/$ROS_VER/setup.bash" ~/.bashrc ||
                    echo "source /opt/ros/$ROS_VER/setup.bash" >> ~/.bashrc

                    grep -F "ROS_MASTER_URI" ~/.bashrc ||
                    echo "export ROS_MASTER_URI=http://localhost:11311" >> ~/.bashrc

                    grep -F "ROS_HOSTNAME" ~/.bashrc ||
                    echo "export ROS_HOSTNAME=localhost" >> ~/.bashrc

                    ls -la $HOME
                    ls -la ~/

                - name : chown
                  run: |
                    sudo chown $USER:$USER $HOME/.ros/ -R
                - name : setup.bash
                  run: |
                    source ~/work/catkin_ws/devel/setup.bash

                - name: package make
                  run: |
                    cd ~/
                    git clone https://github.com/sho6715/pimouse_ros.git
                    rsync -av ~/work/pimouse_ros/pimouse_ros ~/work/catkin_ws/src/
                    cd ${CATKIN_WS}
                    source /opt/ros/noetic/setup.bash
                    catkin_make
                    source ~/work/catkin_ws/devel/setup.bash

                - name: dummy file
                  run: |
                    source ~/work/catkin_ws/devel/setup.bash
                    cd ~/work/catkin_ws/src/pimouse_ros
                    bash -xve ${CATKIN_WS}/src/pimouse_ros/test/travis_prepare_dummy_files.bash
                    ls -la ~/


                    rostest pimouse_ros test.launch


