name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-20.04
                env:
                    CATKIN_WS: /home/runner/work/catkin_ws

                steps:
                - uses: actions/checkout@v2

                - name: ROS setup
                  run: |
                    sudo apt-get install python3
                    pip install --user catkin_pkg
                    pip install --user empy
                    pip install --user pyyaml
                    pip install --user rospkg

                    sudo apt-get update
                    sudo apt-get install -y git
                    sudo apt-get install -y openssh-server

                    UBUNTU_VER=$(lsb_release -sc)
                    ROS_VER=noetic
                    [ "$UBUNTU_VER" = "focal" ] || exit 1

                    echo "deb http://packages.ros.org/ros/ubuntu $UBUNTU_VER main" > /tmp/$$-deb
                    sudo mv /tmp/$$-deb /etc/apt/sources.list.d/ros-latest.list

                - name: ROS setup 2
                  run: |

                    set +vx
                    while ! sudo apt-get install -y curl ; do
                      echo '***WAITING TO GET A LOCK FOR APT...***'
                      sleep 1
                    done

                    curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
                    sudo apt-get update || echo ""

                    sudo apt-get install -y ros-noetic-ros-base


                - name: Get Python version
                  run: python -V

                - name: catkin_make
                  run: |
                    mkdir -p ${CATKIN_WS}/src
                    cd ${CATKIN_WS}/src
                    source /opt/ros/noetic/setup.bash
                    catkin_init_workspace
                    cd ${CATKIN_WS}
                    catkin_make

                - name: setup bash
                  run: |
                    ls /etc/ros/rosdep/sources.list.d/20-default.list && sudo rm -f /etc/ros/rosdep/sources.list.d/20-default.list

                    sudo apt-get install python3-rosdep

                    sudo apt-get update
                    sudo rosdep init 
                    sudo rosdep update

                    grep -F "source /opt/ros/$ROS_VER/setup.bash" ~/.bashrc ||
                    echo "source /opt/ros/$ROS_VER/setup.bash" >> ~/.bashrc

                    grep -F "ROS_MASTER_URI" ~/.bashrc ||
                    echo "export ROS_MASTER_URI=http://localhost:11311" >> ~/.bashrc

                    grep -F "ROS_HOSTNAME" ~/.bashrc ||
                    echo "export ROS_HOSTNAME=localhost" >> ~/.bashrc

                    ls -la $HOME
                    ls -la ~/

                - name : setup.bash
                  run: |
                    source ~/work/catkin_ws/devel/setup.bash

                - name: package make
                  run: |
                    cd ~/
                    git clone https://github.com/sho6715/pimouse_ros.git
                    rsync -av ~/work/pimouse_ros/pimouse_ros ~/work/catkin_ws/src/
                    cd ${CATKIN_WS}
                    source /opt/ros/noetic/setup.bash
                    catkin_make
                    source ~/work/catkin_ws/devel/setup.bash

                - name: dummy file
                  run: |
                    source ~/work/catkin_ws/devel/setup.bash
                    cd ~/work/catkin_ws/src/pimouse_ros
                    bash -xve ${CATKIN_WS}/src/pimouse_ros/test/travis_prepare_dummy_files.bash

                    cd ${CATKIN_WS}/src/
                    ls -la 
                    cd pimouse_ros
                    ls -la

                    whoami

                    cd ${CATKIN_WS}
                    rostest pimouse_ros test.launch


