name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-18.04
                steps:
                        - name: echo command
                          run: echo "Hello World"

                        - name: packages
                          run: 
                                pip install --user catkin_pkg
                                pip install --user empy
                                pip install --user pyyaml
                                pip install --user rospkg

                        - name: ros install
                          run:
                                echo lsb_release -sc
                                UBUNTU_VER=$(lsb_release -sc)
                                ROS_VER=melodic
                                [ "$UBUNTU_VER" = "bionic" ] || exit 1

                                echo "deb http://packages.ros.org/ubuntu $UBUNTU_VER main" > /tmp/$$-deb
                                sudo mv /tmp/$$-deb /etc/apt/sources.list.d/ros-latest.list

                                set +vx
                                while ! sudo apt-get install -y curl 
                                do
                                        echo '***WAITING TO GET A LOCK FOR APT...***'
                                        sleep 1
                                done
                                set -vx

                                curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
                                sudo apt-get update #|| echo ""

                                #sudo apt-get install -y ros-${ROS_VER}-ros-base

