name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-18.04
                steps:
                        - name: echo command
                          run: echo "Hello World"

                        - name: packages
                          run: 
                                pip install --user catkin_pkg
                                pip install --user empy
                                pip install --user pyyaml
                                pip install --user rospkg

