name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-18.04
                env:
                    CATKIN_WS: /home/runner/work/catkin_ws

                steps:
                - uses: actions/checkout@v2

                - name: packages
                  run:
                      pip install --user catkin_pkg
                      pip install --user empy
                      pip install --user pyyaml
                      pip install --user rospkg

                      pip install --upgrade pip

                - name: Setup ROS
                  uses: ros-tooling/setup-ros@v0.2
                  with:
                      required-ros-distributions: melodic
                
                - name: Init workspace
                  run: |
                     ls /etc/ros/rosdep/sources.list.d/20-default.list && sudo rm -f /etc/ros/rosdep/sources.list.d/20-default.list

                     sudo -H pip install rosdep
                     sudo rosdep init
                     rosdep update
                     sudo apt-get install -y python-rosinstall

                     sudo apt-get install -y build-essential

                     grep -F "source /opt/ros/$ROS_VER/setup.bash" ~/.bashrc ||
                     echo "souce /opt/ros/$ROS_VER/setup.bash" >> ~/.bashrc

                     grep -F "ROS_MASTER_URI" ~/.bashrc ||
                     echo "export ROS_MASTER_URI=http://localhost:11311" >> ~/.bashrc

                     grep -F "ROS_HOSTNAME" ~/.bashrc ||
                     echo "export ROS_HOSTNAME=localhost" >> ~/.bashrc

                     source /opt/ros/melodic/setup.bash
                     mkdir -p ${CATKIN_WS}/src && cd ${CATKIN_WS} && catkin_make
                     ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/
                     ls -la
                     pwd
                     cd ~/work/catkin_ws/src
                     ls -la

                - name: Run tests
                  run: |
                     source ${CATKIN_WS}/devel/setup.bash
                     bash -xve ./test/travis_prepare_dummy_files.bash
                     rostest pimouse_ros test.launch 
                        
