name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-20.04
                env:
                    CATKIN_WS: /home/runner/work/catkin_ws

                steps:
                - uses: actions/checkout@v2

                - uses: update ubuntu
                  runs: |
                  apt-get update
                  apt-get upgrade

                - uses: setup python
                  runs: |
                  apt install build-essential 
                  echo "python -v" >> python -v


                - name: Setup_ROS
                  

