name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-18.04
                steps:
                        - uses: actions/checkout@v2
                        - name: echo command
                          run: echo "Hello World"
                        
                        - name: ver check
                          run:
                                echo "$(lsb_release -sc)"
                        - name: ros install
                          run:
                                UBUNTU_VER=$(lsb_release -sc)
                                ROS_VER=melodic

                                [ "$UBUNTU_VER" = "bionic" ] || exit 1

                                sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu UBUNTU_VER main" > /etc/apt/sources.list.d/ros-latest.list'
                                
                                set +vx
                                while ! sudo apt-get install -y curl 
                                do
                                        echo '***WAITING TO GET A LOCK FOR APT...***'
                                        sleep 1
                                        done
                                set -vx

                                curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
                                
                                sudo apt-get update || echo ""

                                sudo apt-get install -y ros-${ROS_VER}-ros-base

