name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-20.04
                env:
                    CATKIN_WS: /home/runner/work/catkin_ws

                steps:
                - uses: actions/checkout@v2

                - name: Setup Python
                  uses: actions/setup-python@v2
                  with:
                    python-version: '3.8'
                    architecture: 'x64'
                - name: Get Python version
                  run: python -V


                - name: Setup_ROS
                  uses: ros-tooling/setup-ros@v0.2
                  with:
                    required-ros-distributions: noetic

