name: ROS test workflow

on: [push]

jobs:
        test:
                runs-on: ubuntu-20.04
                env:
                    CATKIN_WS: /home/runner/work/catkin_ws

                steps:
                - name: Setup_ROS
                  uses: ros-tooling/setup-ros@v0.2
                  with:
                    required-ros-distributions: noetic

                - name: Get Python version
                  run: python -V

                - name: catkin_make
                  run: |
                    mkdir -p ${CATKIN_WS}/src
                    cd ${CATKIN_WS}/src
                    source /opt/ros/noetic/setup.bash
                    catkin_init_workspace
                    cd ${CATKIN_WS}
                    catkin_make

                - name: setup bash
                  run: |
                    grep -F "source /opt/ros/$ROS_VER/setup.bash" ~/.bashrc ||
                    echo "source /opt/ros/$ROS_VER/setup.bash" >> ~/.bashrc

                    grep -F "ROS_MASTER_URI" ~/.bashrc ||
                    echo "export ROS_MASTER_URI=http://localhost:11311" >> ~/.bashrc

                    grep -F "ROS_HOSTNAME" ~/.bashrc ||
                    echo "export ROS_HOSTNAME=localhost" >> ~/.bashrc
                    
                    rsync -av ./ ~/catkin_ws/src/pimouse_ros


